spring:
  datasource :
    hikari :
      maximum-pool-size : 1
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 30000
    jdbc-url : jdbc:mysql://localhost:3306/extjs_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver
    mapper-locations: classpath:/mybatis/mapper/*.xml

mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true